---
- hosts: imageservers
  sudo: yes
  sudo_user: isucon
  gather_facts: no
  tasks:
    - git:
        repo=https://github.com/tagomoris/xbuild.git
        dest=/home/isucon/.xbuild
        update=yes
        force=yes
    # https://twitter.com/matsuu/status/773105183744069633
    - replace: dest=/home/isucon/.xbuild/perl-install regexp='http://cpanmin\.us/' replace='http://git.io/cpanm'
    # ruby
    - command: /home/isucon/.xbuild/ruby-install 2.2.3 /home/isucon/.local/ruby
      args:
        creates: /home/isucon/.local/ruby/bin/ruby
    # python3
    - command: /home/isucon/.xbuild/python-install 3.4.3 /home/isucon/.local/python3
      args:
        creates: /home/isucon/.local/python3/bin/python
    
- hosts: imageservers
  sudo: yes
  gather_facts: no
  tasks:
    # java
    - apt: name=openjdk-8-jdk state=present
